"""`indicators`: technical indicators on each stock's candle history.

Every pandas-ta-classic indicator (and TA-Lib's candlestick patterns) is a method, built from
`indicator_catalog.json` (generated by `sdk/tools/build_indicators.py`):

    indicators.rsi(period=14)            -> latest value (float), or None without enough history
    indicators.macd().histogram          -> named fields for multi-value indicators
    indicators.cdl_engulfing()           -> 100 bullish, -100 bearish, 0 none
    indicators.series("ema", period=9)   -> full history (pandas Series / DataFrame)
"""

import inspect
import json
import math
from collections import namedtuple
from collections.abc import Callable
from pathlib import Path

import pandas as pd
import pandas_ta_classic as ta

MAX_ROWS = 1000  # history kept per stock
COLUMNS = ["open", "high", "low", "close", "volume"]
CATALOG_PATH = Path(__file__).with_name("indicator_catalog.json")


def load_catalog() -> list[dict]:
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8")) if CATALOG_PATH.exists() else []


def _scalar(value):
    """A cell as a plain Python value: float for numbers (None for NaN/inf), text as-is."""
    if value is None:
        return None
    if isinstance(value, str):
        return value
    try:
        f = float(value)
    except (TypeError, ValueError):
        return value
    return f if math.isfinite(f) else None


def _last(value):
    if isinstance(value, (pd.Series, pd.DataFrame)):
        if len(value) == 0:
            return None
        value = value.iloc[-1]
    return _scalar(value)


def _first_output(out):
    """pandas-ta returns a Series, a DataFrame, or occasionally a tuple whose first item is the result."""
    if isinstance(out, tuple):
        out = out[0] if out else None
    return out


def _as_series(x, name: str) -> pd.Series:
    if isinstance(x, pd.DataFrame):
        if x.shape[1] != 1:
            raise TypeError(f"{name} must be a single series, not a table with columns {list(x.columns)}")
        x = x.iloc[:, 0]
    if not isinstance(x, pd.Series):
        raise TypeError(f"{name} must be a pandas Series or a number")
    return x


def _tuple_type(entry: dict, names: list[str]):
    key = (entry["name"], tuple(names))
    cached = _TUPLES.get(key)
    if cached is None:
        type_name = "".join(part.title() for part in entry["name"].split("_")) or "Values"
        cached = _TUPLES[key] = namedtuple(type_name, names)
    return cached


_TUPLES: dict = {}


def _safe_field(name: str, used: set) -> str:
    field = "".join(c if c.isalnum() else "_" for c in str(name).lower()).strip("_") or "value"
    if field[0].isdigit():
        field = "v_" + field
    while field in used:
        field += "_"
    used.add(field)
    return field


def _field_names(entry: dict, frame: pd.DataFrame) -> tuple[list[str], list[int]]:
    """(field names, column positions): the catalog's names when the columns match, else derived ones."""
    spec = entry["returns"]
    if spec.get("fields") and frame.shape[1] == len(spec["fields"]):
        return spec["fields"], spec["columns"]
    used: set = set()
    return [_safe_field(c, used) for c in frame.columns], list(range(frame.shape[1]))


def _signature(entry: dict) -> inspect.Signature:
    P = inspect.Parameter
    params = [P("self", P.POSITIONAL_OR_KEYWORD)]
    params += [P(p["name"], P.POSITIONAL_OR_KEYWORD, default=p["default"]) for p in entry["params"]]
    params.append(P("symbol", P.KEYWORD_ONLY, default=None))
    return inspect.Signature(params)


def _doc(entry: dict) -> str:
    spec = entry["returns"]
    returns = {
        "value": "Latest value (float), or None while there isn't enough history.",
        "pattern": "100 bullish, -100 bearish, 0 no pattern (latest candle); None without data.",
        "table": "A pandas DataFrame for the whole history.",
    }.get(spec["kind"]) or f"Named fields: {', '.join(spec.get('fields', []))} (each None while there isn't enough history)."
    lines = [entry["title"] + ".", "", returns]
    if entry.get("pair"):
        lines.append("other: another stock in this run's universe to compare with.")
    if entry.get("notes"):
        lines.append(entry["notes"])
    lines += [f"{p['name']} defaults to {p['same_as']}." for p in entry["params"] if p.get("same_as")]
    return "\n".join(lines)


def _make_method(entry: dict):
    sig = _signature(entry)
    has_period = any(p["name"] == "period" for p in entry["params"])

    def method(self, *args, **kwargs):
        if has_period and "length" in kwargs and "period" not in kwargs:
            kwargs["period"] = kwargs.pop("length")
        bound = sig.bind(self, *args, **kwargs)
        params = {k: v for k, v in bound.arguments.items() if k not in ("self", "symbol")}
        return self._latest(entry, params, bound.arguments.get("symbol"))

    method.__name__ = method.__qualname__ = entry["name"]
    method.__signature__ = sig
    method.__doc__ = _doc(entry)
    return method


class Indicators:
    """Indicator shortcuts for the stocks in a run (see `available()` for the full list)."""

    def __init__(self, universe: list[str], current: Callable[[], str], catalog: list[dict] | None = None) -> None:
        self._frames: dict[str, pd.DataFrame] = {}
        self._universe = universe
        self._current = current
        self._catalog = {e["name"]: e for e in _CATALOG} if catalog is None else {e["name"]: e for e in catalog}
        if catalog is not None:  # a catalog other than the packaged one (used by the generator)
            for entry in catalog:
                setattr(self, entry["name"], _make_method(entry).__get__(self))

    # --- data management (used by the runner) --------------------------------------

    def load(self, symbol: str, bars: list[dict]) -> None:
        df = pd.DataFrame(bars, columns=["time", *COLUMNS])
        df.index = pd.to_datetime(df.pop("time"), unit="s", utc=True).dt.tz_convert("Asia/Kolkata")
        self._frames[symbol] = df.astype(dict.fromkeys(COLUMNS, float)).tail(MAX_ROWS)

    def append(self, symbol: str, bar: dict) -> None:
        ts = pd.to_datetime(bar["time"], unit="s", utc=True).tz_convert("Asia/Kolkata")
        row = pd.DataFrame([[float(bar[k]) for k in COLUMNS]], columns=COLUMNS, index=[ts])
        df = self._frames.get(symbol)
        df = row if df is None or df.empty else pd.concat([df[df.index < ts], row])
        self._frames[symbol] = df.tail(MAX_ROWS)

    # --- user-facing helpers ----------------------------------------------------------

    def df(self, symbol: str | None = None) -> pd.DataFrame:
        """OHLCV history of a stock (DatetimeIndex in IST), for anything pandas-ta-classic offers via `.ta`."""
        return self._frame(symbol).copy()

    def available(self) -> dict[str, str]:
        """Every indicator shortcut: {name: description}."""
        return {name: e["title"] for name, e in sorted(self._catalog.items())}

    def series(self, name: str, *, symbol: str | None = None, **params):
        """Full history of an indicator: a Series, or a DataFrame whose columns are the field names.

        indicators.series("ema", period=9)          # Series
        indicators.series("macd").histogram          # DataFrame column
        """
        entry = self._entry(name)
        if "length" in params and "period" not in params:
            params["period"] = params.pop("length")
        known = {p["name"] for p in entry["params"]}
        unknown = set(params) - known
        if unknown:
            raise TypeError(f"{name}() got unexpected parameter(s) {', '.join(sorted(unknown))}; it takes {', '.join(sorted(known)) or 'none'}")
        out = self._compute(entry, params, symbol)
        kind = entry["returns"]["kind"]
        if out is None:
            return pd.DataFrame() if kind in ("fields", "table") else pd.Series(dtype=float)
        if kind == "fields" and isinstance(out, pd.DataFrame):
            names, cols = _field_names(entry, out)
            out = out.iloc[:, cols].copy()
            out.columns = names
        elif kind in ("value", "pattern") and isinstance(out, pd.DataFrame):
            out = out.iloc[:, 0]
        return out

    @staticmethod
    def crossed_above(a, b) -> bool:
        """True if `a` crossed above `b` on the latest candle (a Series against a Series or a number)."""
        return Indicators._crossed(a, b, above=True)

    @staticmethod
    def crossed_below(a, b) -> bool:
        """True if `a` crossed below `b` on the latest candle (a Series against a Series or a number)."""
        return Indicators._crossed(a, b, above=False)

    # --- internals ------------------------------------------------------------------------

    @staticmethod
    def _crossed(a, b, above: bool) -> bool:
        a_num, b_num = isinstance(a, (int, float)), isinstance(b, (int, float))
        if a_num and b_num:
            raise TypeError("crossed_above/crossed_below need a history; pass indicators.series(...) for at least one side")
        if a_num:
            b = _as_series(b, "b")
            a = pd.Series(float(a), index=b.index)
        else:
            a = _as_series(a, "a")
            b = pd.Series(float(b), index=a.index) if b_num else _as_series(b, "b")
        n = min(len(a), len(b))  # align on the most recent values
        both = pd.concat([a.iloc[len(a) - n:].reset_index(drop=True), b.iloc[len(b) - n:].reset_index(drop=True)], axis=1).dropna()
        if len(both) < 2:
            return False
        (pa, pb), (ca, cb) = both.iloc[-2], both.iloc[-1]
        return bool(pa <= pb and ca > cb) if above else bool(pa >= pb and ca < cb)

    def _entry(self, name: str) -> dict:
        entry = self._catalog.get(name)
        if entry is None:
            raise AttributeError(f"No indicator named {name!r}; indicators.available() lists them")
        return entry

    def _latest(self, entry: dict, params: dict, symbol: str | None):
        out = self._compute(entry, params, symbol)
        kind = entry["returns"]["kind"]
        if kind == "table":
            return out if isinstance(out, pd.DataFrame) else pd.DataFrame()
        if kind == "fields":
            if not isinstance(out, pd.DataFrame) or out.empty:
                names = entry["returns"]["fields"]
                return _tuple_type(entry, names)(*[None] * len(names))
            names, cols = _field_names(entry, out)
            row = out.iloc[-1]
            values = [_scalar(row.iloc[c]) for c in cols]
            values = [int(v) if n == "direction" and isinstance(v, float) else v for n, v in zip(names, values)]
            return _tuple_type(entry, names)(*values)
        if isinstance(out, pd.DataFrame):
            out = out.iloc[:, 0] if out.shape[1] else None
        value = _last(out)
        if kind == "pattern" and isinstance(value, float):
            return int(value)
        return value

    def _compute(self, entry: dict, params: dict, symbol: str | None):
        frame = self._frame(symbol)
        if frame.empty:
            return None
        kwargs = {**entry.get("overrides", {}), **entry["fixed"]}
        by_name = {p["name"]: p for p in entry["params"]}
        for name, value in params.items():
            p = by_name[name]
            # Documented defaults are left to pandas-ta, which treats some flags as "set" whenever passed.
            if value is not None and not (value == p["default"] and p["arg"] not in kwargs):
                kwargs[p["arg"]] = value
        if entry.get("pair"):
            other = kwargs.pop("benchmark", None)
            if not other:
                raise ValueError(f"{entry['name']}() needs other=<symbol>, another stock in this run")
            kwargs["benchmark"] = self._frame(other)["close"].reindex(frame.index)
        for col in entry["inputs"]:
            kwargs["open_" if col == "open" else col] = frame[col]
        fn = getattr(ta, entry["function"])
        return _first_output(fn(**kwargs))

    def _resolve(self, symbol: str | None) -> str:
        sym = (symbol or self._current()).upper()
        if sym not in self._universe:
            raise ValueError(f"{sym} isn't in this run's symbols {self._universe}; add it in the Run dialog or SYMBOLS")
        return sym

    def _frame(self, symbol: str | None) -> pd.DataFrame:
        return self._frames.get(self._resolve(symbol), pd.DataFrame(columns=COLUMNS))


_CATALOG = load_catalog()
for _entry in _CATALOG:
    setattr(Indicators, _entry["name"], _make_method(_entry))
